version: '3.3'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    networks:
      - sonarnet
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:alpine
    depends_on:
      - db
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db/sonar
    networks:
      - sonarnet
    ports:
      - "9000:9000"
    privileged: true
    volumes:
      - ./extensions:/opt/sonarqube/extensions
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  sonarnet:

volumes:
  postgresql_data:
