version: '3.3'
# login: user
# password: bitnami
services:
  jenkins:
    # image: 'bitnami/jenkins:2'
    image: dirane/jenkins-docker-ansible-clair
    ports:
      - '8080:8080'
      - '8443:8443'
      - '50000:50000'
    privileged: true
    volumes:
      - 'jenkins_data:/bitnami'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'jenkins_home:/opt/'
volumes:
  jenkins_data:
    driver: local
  jenkins_home:
    driver: local
